export SocialValidation from "./components/SocialValidation";
export Divider from "./components/Divider";
export EmployerReviews from "./components/EmployerReviews";
export LandingPageHero from "./components/LandingPageHero";
export RightFeatures from "./components/RightFeatures";
export LeftFeatures from "./components/LeftFeatures";
export Benefits from "./components/Benefits";
export Backers from './components/Backers'
export AltFeature from './components/AltFeature'
export StudentTestimonials from './components/StudentTestimonials'
export Prizes from './components/Prizes'