[build]
  publish = "public"
  command = "npm run build"
	functions = "./func"

[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"

[context.branch-deploy.environment]
  APP_URL = "https://app.01-staging.univjobs.ca/"
  STATIC_URL = "https://01-staging.univjobs.ca/"

  BRANCH = "staging 01"

[context.master.environment] # 'staging' is a branch name
  BRANCH = "staging 02"

[context.production.environment]
  APP_URL = "https://app.univjobs.ca/"
  STATIC_URL = "https://univjobs.ca/"

  BRANCH = "production"