[build]
  publish = "public"
  command = "npm run build"
	functions = "./func"

[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"

[context.master.environment]
  APP_URL = "https://app.01-staging.univjobs.ca/"
  STATIC_URL = "https://01-staging.univjobs.ca/"

[context.production.environment]
  APP_URL = "https://app.univjobs.ca/"
  STATIC_URL = "https://univjobs.ca/"