export default [
  { value: 0, label: 'Accounting' },
  { value: 1, label: 'Airlines/Aviation' },
  { value: 2, label: 'Alternative Medicine' },
  { value: 3, label: 'Animation' },
  { value: 4, label: 'Apparel and Fashion' },
  { value: 5, label: 'Architecture and Planning' },
  { value: 6, label: 'Arts and Crafts' },
  { value: 7, label: 'Automotive' },
  { value: 8, label: 'Aviation and Aerospace' },
  { value: 9, label: 'Banking' },
  { value: 10, label: 'Biotechnology' },
  { value: 11, label: 'Broadccast Media' },
  { value: 12, label: 'Capital Markets' },
  { value: 13, label: 'Chemicals' },
  { value: 14, label: 'Civic and Social Orgization' },
  { value: 15, label: 'Civil Engineering' },
  { value: 16, label: 'Commercial Real Estate' },
  { value: 17, label: 'Computer Games' },
  { value: 18, label: 'Computer Hardware' },
  { value: 19, label: 'Computer Software' },
  { value: 20, label: 'Consumer Goods' },
  { value: 21, label: 'Cosmetics' },
  { value: 22, label: 'Defense and Space' },
  { value: 23, label: 'Design' },
  { value: 26, label: 'E-learning' },
  { value: 24, label: 'Education' },
  { value: 25, label: 'Education Management' },
  { value: 27, label: 'Electrical/Electronic Manufacturing' },
  { value: 28, label: 'Entertainment' },
  { value: 29, label: 'Environmental Services' },
  { value: 30, label: 'Event Services' },
  { value: 31, label: 'Executive Office' },
  { value: 32, label: 'Facilities Services' },
  { value: 33, label: 'Financial Services' },
  { value: 34, label: 'Fine Art' },
  { value: 35, label: 'Food and Beverages' },
  { value: 36, label: 'Food Production' },
  { value: 37, label: 'Fund-Raising' },
  { value: 38, label: 'Furniture' },
  { value: 39, label: 'Gambling and Casinos' },
  { value: 40, label: 'Glass Ceramics Textile and Concrete' },
  { value: 41, label: 'Goverment Administration' },
  { value: 42, label: 'Graphic Design' },
  { value: 43, label: 'Health Wellness and Fitness' },
  { value: 44, label: 'Higher Education' },
  { value: 45, label: 'Hospital and Health Care' },
  { value: 46, label: 'Hospitality' },
  { value: 47, label: 'Human Resources' },
  { value: 48, label: 'Indivvalueual and Family Services' },
  { value: 49, label: 'Information Services' },
  { value: 50, label: 'Information Technology and Services' },
  { value: 51, label: 'Insurance' },
  { value: 52, label: 'International Affairs' },
  { value: 53, label: 'International Trade and Development' },
  { value: 54, label: 'Internet' },
  { value: 55, label: 'Investing' },
  { value: 56, label: 'Investment Management' },
  { value: 57, label: 'Judiciary' },
  { value: 58, label: 'Law Enforcement' },
  { value: 59, label: 'Law Practice' },
  { value: 60, label: 'Legal Services' },
  { value: 61, label: 'Legislative Office' },
  { value: 62, label: 'Leisure Travel and Tourism' },
  { value: 63, label: 'Libraries' },
  { value: 64, label: 'Logistics and Supply Chain' },
  { value: 65, label: 'Luxury Goods and Jewelry' },
  { value: 66, label: 'Machinery' },
  { value: 67, label: 'Management Consulting' },
  { value: 68, label: 'Maritime' },
  { value: 70, label: 'Market Research' },
  { value: 69, label: 'Marketing and Advertising' },
  { value: 71, label: 'Mechanical or Industrial Engineering' },
  { value: 72, label: 'Media Production' },
  { value: 73, label: 'Medical Devices' },
  { value: 74, label: 'Medical Practice' },
  { value: 75, label: 'Mental Health Care' },
  { value: 76, label: 'Military' },
  { value: 77, label: 'Motion Pictures and Film' },
  { value: 78, label: 'Museums and Institutions' },
  { value: 79, label: 'Music' },
  { value: 80, label: 'Newspaper' },
  { value: 81, label: 'Non-Profit' },
  { value: 82, label: 'Oil and Energy' },
  { value: 83, label: 'Online Media' },
  { value: 84, label: 'Other' },
  { value: 85, label: 'Package/Freight Delivery' },
  { value: 86, label: 'Performing Arts' },
  { value: 87, label: 'Pharmaceuticals' },
  { value: 88, label: 'Philantrophy' },
  { value: 89, label: 'Photography' },
  { value: 90, label: 'Plastics' },
  { value: 91, label: 'Political Organization' },
  { value: 92, label: 'Primary/Secondary Education' },
  { value: 93, label: 'Printing' },
  { value: 94, label: 'Professional Training and Coaching' },
  { value: 95, label: 'Program Development' },
  { value: 96, label: 'Public Policy' },
  { value: 97, label: 'Public Relations and Communications' },
  { value: 98, label: 'Public Safety' },
  { value: 99, label: 'Publishing' },
  { value: 100, label: 'Real Estate' },
  { value: 101, label: 'Religious Institutions' },
  { value: 102, label: 'Renewables and Environment' },
  { value: 103, label: 'Research' },
  { value: 104, label: 'Retail' },
  { value: 105, label: 'Security and Investigations' },
  { value: 106, label: 'Service' },
]
