export default [
  { value: 0, label: 'Accounting' },
  { value: 1, label: 'Agriculture & Forestry' },
  { value: 2, label: 'Banking & Finance' },
  { value: 3, label: 'Business, Admin & Management' },
  { value: 4, label: 'Construction & Skilled Trades' },
  { value: 6, label: 'Consulting' },
  { value: 7, label: 'Consumer Packaged Goods' },
  { value: 8, label: 'Defense and Space' },
  { value: 9, label: 'Diversity' },
  { value: 10, label: 'Education' },
  { value: 11, label: 'Engineering' },
  { value: 12, label: 'Entertainment' },
  { value: 13, label: 'Fashion, Design & Beauty' },
  { value: 14, label: 'Financial Services' },
  { value: 15, label: 'Fitness & Recreation' },
  { value: 16, label: 'Government' },
  { value: 17, label: 'Healthcare' },
  { value: 18, label: 'Hospitality' },
  { value: 19, label: 'HR' },
  { value: 20, label: 'Insurance' },
  { value: 21, label: 'IT' },
  { value: 22, label: 'Journalism' },
  { value: 23, label: 'Law' },
  { value: 24, label: 'Manufacturing' },
  { value: 25, label: 'Marketing, Media & Creative' },
  { value: 26, label: 'Mining' },
  { value: 27, label: 'Non-profit' },
  { value: 28, label: 'Oil & Gas' },
  { value: 29, label: 'Real Estate' },
  { value: 30, label: 'Retail' },
  { value: 31, label: 'Sales' },
  { value: 32, label: 'Science and Research' },
  { value: 33, label: 'Social Services' },
  { value: 34, label: 'Software Engineering' },
  { value: 35, label: 'Tax' },
  { value: 36, label: 'Telecommunication' },
  { value: 37, label: 'Transportation' },
  { value: 38, label: 'Travel' },
  { value: 39, label: 'Service' }
]
